//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sr.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photoes
    {
        public int Id_Photo { get; set; }
        public byte[] Photo { get; set; }
        public string Text { get; set; }
        public Nullable<int> Id_Pet { get; set; }
    
        public virtual Pet Pet { get; set; }
    }
}
